import { Task, DailyTaskSet, WeeklyTaskSet, AchievementChapter, TaskCategory } from "../types/tasks";

// Daily task rotation by weekday (0 = Sunday, 1 = Monday, etc.)
export const dailyTaskSets: DailyTaskSet[] = [
  {
    weekday: 1, // Monday
    tasks: [
      {
        id: "daily-visit-mon",
        title: "Visit the app today",
        description: "Open the app once today",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "visit" as TaskCategory,
        icon: "📱",
      },
      {
        id: "daily-eco-mon",
        title: "Ask Eco Assistant",
        description: "Ask the Eco Assistant a question",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "eco_assistant" as TaskCategory,
        icon: "🤖",
      },
      {
        id: "daily-map-mon",
        title: "Open Recycling Map",
        description: "Open the recycling map",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "map" as TaskCategory,
        icon: "🗺️",
      },
    ],
  },
  {
    weekday: 2, // Tuesday
    tasks: [
      {
        id: "daily-scan-tue",
        title: "Scan waste item",
        description: "Scan one waste item",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "scan" as TaskCategory,
        icon: "📸",
      },
      {
        id: "daily-guide-tue",
        title: "Read Recycling Guide",
        description: "Read the recycling guide",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "recycling" as TaskCategory,
        icon: "📖",
      },
      {
        id: "daily-leaderboard-tue",
        title: "Visit Leaderboard",
        description: "Check the leaderboard",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "leaderboard" as TaskCategory,
        icon: "🏆",
      },
    ],
  },
  {
    weekday: 3, // Wednesday
    tasks: [
      {
        id: "daily-eco-wed",
        title: "Ask Eco Twice",
        description: "Ask Eco Assistant 2 questions",
        reward: 5,
        target: 2,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "eco_assistant" as TaskCategory,
        icon: "🤖",
      },
      {
        id: "daily-profile-wed",
        title: "Open Profile",
        description: "Open your profile page",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "profile" as TaskCategory,
        icon: "👤",
      },
      {
        id: "daily-map-wed",
        title: "Open Recycling Map",
        description: "Open the recycling map",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "map" as TaskCategory,
        icon: "🗺️",
      },
    ],
  },
  {
    weekday: 4, // Thursday
    tasks: [
      {
        id: "daily-scan-thu",
        title: "Scan waste item",
        description: "Scan one waste item",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "scan" as TaskCategory,
        icon: "📸",
      },
      {
        id: "daily-leaderboard-thu",
        title: "Visit Leaderboard",
        description: "Check the leaderboard",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "leaderboard" as TaskCategory,
        icon: "🏆",
      },
      {
        id: "daily-settings-thu",
        title: "Visit Settings",
        description: "Visit the settings page",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "settings" as TaskCategory,
        icon: "⚙️",
      },
    ],
  },
  {
    weekday: 5, // Friday
    tasks: [
      {
        id: "daily-eco-fri",
        title: "Ask Eco Assistant",
        description: "Ask the Eco Assistant a question",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "eco_assistant" as TaskCategory,
        icon: "🤖",
      },
      {
        id: "daily-scan-fri",
        title: "Scan waste item",
        description: "Scan one waste item",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "scan" as TaskCategory,
        icon: "📸",
      },
      {
        id: "daily-map-fri",
        title: "Open Recycling Map",
        description: "Open the recycling map",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "map" as TaskCategory,
        icon: "🗺️",
      },
    ],
  },
  {
    weekday: 6, // Saturday
    tasks: [
      {
        id: "daily-visit-sat",
        title: "Visit the app today",
        description: "Open the app once today",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "visit" as TaskCategory,
        icon: "📱",
      },
      {
        id: "daily-achievements-sat",
        title: "Read Achievements",
        description: "Read your achievements",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "recycling" as TaskCategory,
        icon: "🏆",
      },
      {
        id: "daily-eco-sat",
        title: "Ask Eco Assistant",
        description: "Ask the Eco Assistant a question",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "eco_assistant" as TaskCategory,
        icon: "🤖",
      },
    ],
  },
  {
    weekday: 0, // Sunday
    tasks: [
      {
        id: "daily-visit-sun",
        title: "Visit the app today",
        description: "Open the app once today",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "visit" as TaskCategory,
        icon: "📱",
      },
      {
        id: "daily-leaderboard-sun",
        title: "Visit Leaderboard",
        description: "Check the leaderboard",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "leaderboard" as TaskCategory,
        icon: "🏆",
      },
      {
        id: "daily-map-sun",
        title: "Open Recycling Map",
        description: "Open the recycling map",
        reward: 5,
        target: 1,
        current: 0,
        completed: false,
        claimed: false,
        type: "daily",
        category: "map" as TaskCategory,
        icon: "🗺️",
      },
    ],
  },
];

// Weekly task rotation sets
export const weeklyTaskSets: WeeklyTaskSet[] = [
  {
    id: "week-set-a",
    title: "Week Set A",
    tasks: [
      {
        id: "weekly-scans-a",
        title: "Scanner Pro",
        description: "Complete 5 scans this week",
        reward: 50,
        target: 5,
        current: 0,
        completed: false,
        claimed: false,
        type: "weekly",
        category: "scan" as TaskCategory,
        icon: "📸",
      },
      {
        id: "weekly-points-a",
        title: "Eco Points Master",
        description: "Earn 100 eco points this week",
        reward: 75,
        target: 100,
        current: 0,
        completed: false,
        claimed: false,
        type: "weekly",
        category: "points" as TaskCategory,
        icon: "🏆",
      },
      {
        id: "weekly-streak-a",
        title: "5 Day Streak",
        description: "Visit the app 5 days in a row",
        reward: 50,
        target: 5,
        current: 0,
        completed: false,
        claimed: false,
        type: "weekly",
        category: "streak" as TaskCategory,
        icon: "🔥",
      },
    ],
    durationWeeks: 2,
  },
  {
    id: "week-set-b",
    title: "Week Set B",
    tasks: [
      {
        id: "weekly-questions-b",
        title: "Question Master",
        description: "Ask Eco Assistant 15 questions",
        reward: 40,
        target: 15,
        current: 0,
        completed: false,
        claimed: false,
        type: "weekly",
        category: "eco_assistant" as TaskCategory,
        icon: "🤖",
      },
      {
        id: "weekly-map-b",
        title: "Map Explorer",
        description: "Open Recycling Map 7 times",
        reward: 30,
        target: 7,
        current: 0,
        completed: false,
        claimed: false,
        type: "weekly",
        category: "map" as TaskCategory,
        icon: "🗺️",
      },
      {
        id: "weekly-streak-b",
        title: "7 Day Streak",
        description: "Visit the app 7 days in a row",
        reward: 50,
        target: 7,
        current: 0,
        completed: false,
        claimed: false,
        type: "weekly",
        category: "streak" as TaskCategory,
        icon: "🔥",
      },
    ],
    durationWeeks: 2,
  },
  {
    id: "week-set-c",
    title: "Week Set C",
    tasks: [
      {
        id: "weekly-points-c",
        title: "Point Hunter",
        description: "Reach 200 eco points",
        reward: 75,
        target: 200,
        current: 0,
        completed: false,
        claimed: false,
        type: "weekly",
        category: "points" as TaskCategory,
        icon: "🏆",
      },
      {
        id: "weekly-scans-c",
        title: "Double Scanner",
        description: "Complete 10 waste scans",
        reward: 50,
        target: 10,
        current: 0,
        completed: false,
        claimed: false,
        type: "weekly",
        category: "scan" as TaskCategory,
        icon: "📸",
      },
      {
        id: "weekly-streak-c",
        title: "Streak Keeper",
        description: "Maintain a 7-day streak",
        reward: 50,
        target: 7,
        current: 0,
        completed: false,
        claimed: false,
        type: "weekly",
        category: "streak" as TaskCategory,
        icon: "🔥",
      },
    ],
    durationWeeks: 3,
  },
];

// Achievement chapters
export const achievementChapters: AchievementChapter[] = [
  {
    id: 1,
    title: "Beginner",
    description: "Start your eco journey",
    icon: "🌱",
    requiredPoints: 0,
    achievements: [
      {
        id: "achievement-first-login",
        title: "First Login",
        description: "Log in to the app for the first time",
        reward: 0,
        target: 1,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "visit" as TaskCategory,
        icon: "📱",
        chapter: 1,
        chapterTitle: "Beginner",
      },
      {
        id: "achievement-first-scan",
        title: "First Scan",
        description: "Complete your first waste scan",
        reward: 0,
        target: 1,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "scan" as TaskCategory,
        icon: "📸",
        chapter: 1,
        chapterTitle: "Beginner",
      },
      {
        id: "achievement-first-eco-question",
        title: "First Question",
        description: "Ask Eco Assistant your first question",
        reward: 0,
        target: 1,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "eco_assistant" as TaskCategory,
        icon: "🤖",
        chapter: 1,
        chapterTitle: "Beginner",
      },
      {
        id: "achievement-first-recycling-visit",
        title: "First Recycling Visit",
        description: "Open the Recycling Map for the first time",
        reward: 0,
        target: 1,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "map" as TaskCategory,
        icon: "🗺️",
        chapter: 1,
        chapterTitle: "Beginner",
      },
    ],
    unlocked: true,
    completed: false,
  },
  {
    id: 2,
    title: "Intermediate",
    description: "Become an eco enthusiast",
    icon: "🌿",
    requiredPoints: 250,
    achievements: [
      {
        id: "achievement-25-scans",
        title: "Scanner Pro",
        description: "Complete 25 waste scans",
        reward: 0,
        target: 25,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "scan" as TaskCategory,
        icon: "📸",
        chapter: 2,
        chapterTitle: "Intermediate",
      },
      {
        id: "achievement-20-questions",
        title: "Curious Mind",
        description: "Ask Eco Assistant 20 questions",
        reward: 0,
        target: 20,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "eco_assistant" as TaskCategory,
        icon: "🤖",
        chapter: 2,
        chapterTitle: "Intermediate",
      },
      {
        id: "achievement-7-day-streak",
        title: "Streak Champion",
        description: "Maintain a 7-day streak",
        reward: 0,
        target: 7,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "streak" as TaskCategory,
        icon: "🔥",
        chapter: 2,
        chapterTitle: "Intermediate",
      },
      {
        id: "achievement-complete-weekly",
        title: "Weekly Warrior",
        description: "Complete all weekly tasks",
        reward: 0,
        target: 3,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "recycling" as TaskCategory,
        icon: "⚔️",
        chapter: 2,
        chapterTitle: "Intermediate",
      },
    ],
    unlocked: false,
    completed: false,
  },
  {
    id: 3,
    title: "Advanced",
    description: "Master of recycling",
    icon: "🌳",
    requiredPoints: 500,
    achievements: [
      {
        id: "achievement-75-scans",
        title: "Scanning Master",
        description: "Complete 75 waste scans",
        reward: 0,
        target: 75,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "scan" as TaskCategory,
        icon: "📸",
        chapter: 3,
        chapterTitle: "Advanced",
      },
      {
        id: "achievement-14-day-streak",
        title: "Two Week Champion",
        description: "Maintain a 14-day streak",
        reward: 0,
        target: 14,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "streak" as TaskCategory,
        icon: "🔥",
        chapter: 3,
        chapterTitle: "Advanced",
      },
      {
        id: "achievement-recycling-hero",
        title: "Recycling Hero",
        description: "Earn 500 eco points",
        reward: 0,
        target: 500,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "points" as TaskCategory,
        icon: "♻️",
        chapter: 3,
        chapterTitle: "Advanced",
      },
      {
        id: "achievement-earth-guardian",
        title: "Earth Guardian",
        description: "Earn 1000 eco points",
        reward: 0,
        target: 1000,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "points" as TaskCategory,
        icon: "🌍",
        chapter: 3,
        chapterTitle: "Advanced",
      },
    ],
    unlocked: false,
    completed: false,
  },
];

// Helper function to get daily tasks for current weekday
export function getDailyTasksForWeekday(weekday: number): Task[] {
  const taskSet = dailyTaskSets.find((set) => set.weekday === weekday);
  return taskSet ? taskSet.tasks : [];
}

// Helper function to get weekly tasks for current set
export function getWeeklyTasksForSet(setId: string): Task[] {
  const taskSet = weeklyTaskSets.find((set) => set.id === setId);
  return taskSet ? taskSet.tasks : [];
}
