import { AchievementChapter } from "../types/tasks";
import { Messages } from "../types/messages";

export function getAchievementChapters(
  messages: Messages,
): AchievementChapter[] {
  return [
    {
      id: 1,
      title: messages.tasks.chapter1,
      description: messages.tasks.chapter1Desc,
      icon: "🌱",
      requiredPoints: 0,
      achievements: [
        {
          id: "achievement-first-login",
          title: messages.tasks.achievementFirstLogin,
          description: messages.tasks.achievementFirstLoginDesc,
          reward: 0,
          target: 1,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "visit",
          icon: "📱",
          chapter: 1,
          chapterTitle: messages.tasks.chapter1,
        },
        {
          id: "achievement-first-scan",
          title: messages.tasks.achievementFirstScan,
          description: messages.tasks.achievementFirstScanDesc,
          reward: 0,
          target: 1,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "scan",
          icon: "📸",
          chapter: 1,
          chapterTitle: messages.tasks.chapter1,
        },
        {
          id: "achievement-first-eco-question",
          title: messages.tasks.achievementFirstEcoQuestion,
          description: messages.tasks.achievementFirstEcoQuestionDesc,
          reward: 0,
          target: 1,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "eco_assistant",
          icon: "🤖",
          chapter: 1,
          chapterTitle: messages.tasks.chapter1,
        },
        {
          id: "achievement-first-recycling-visit",
          title: messages.tasks.achievementFirstRecyclingVisit,
          description: messages.tasks.achievementFirstRecyclingVisitDesc,
          reward: 0,
          target: 1,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "map",
          icon: "🗺️",
          chapter: 1,
          chapterTitle: messages.tasks.chapter1,
        },
      ],
      unlocked: true,
      completed: false,
    },
    {
      id: 2,
      title: messages.tasks.chapter2,
      description: messages.tasks.chapter2Desc,
      icon: "🌿",
      requiredPoints: 250,
      achievements: [
        {
          id: "achievement-25-scans",
          title: messages.tasks.achievement25Scans,
          description: messages.tasks.achievement25ScansDesc,
          reward: 0,
          target: 25,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "scan",
          icon: "📸",
          chapter: 2,
          chapterTitle: messages.tasks.chapter2,
        },
        {
          id: "achievement-20-questions",
          title: messages.tasks.achievement20Questions,
          description: messages.tasks.achievement20QuestionsDesc,
          reward: 0,
          target: 20,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "eco_assistant",
          icon: "🤖",
          chapter: 2,
          chapterTitle: messages.tasks.chapter2,
        },
        {
          id: "achievement-7-day-streak",
          title: messages.tasks.achievementStreakChampion,
          description: messages.tasks.achievementStreakChampionDesc,
          reward: 0,
          target: 7,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "streak",
          icon: "🔥",
          chapter: 2,
          chapterTitle: messages.tasks.chapter2,
        },
        {
          id: "achievement-complete-weekly",
          title: messages.tasks.achievementCompleteWeekly,
          description: messages.tasks.achievementCompleteWeeklyDesc,
          reward: 0,
          target: 3,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "recycling",
          icon: "⚔️",
          chapter: 2,
          chapterTitle: messages.tasks.chapter2,
        },
      ],
      unlocked: false,
      completed: false,
    },
    {
      id: 3,
      title: messages.tasks.chapter3,
      description: messages.tasks.chapter3Desc,
      icon: "🌳",
      requiredPoints: 500,
      achievements: [
        {
          id: "achievement-75-scans",
          title: messages.tasks.achievement75Scans,
          description: messages.tasks.achievement75ScansDesc,
          reward: 0,
          target: 75,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "scan",
          icon: "📸",
          chapter: 3,
          chapterTitle: messages.tasks.chapter3,
        },
        {
          id: "achievement-14-day-streak",
          title: messages.tasks.achievement14DayStreak,
          description: messages.tasks.achievement14DayStreakDesc,
          reward: 0,
          target: 14,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "streak",
          icon: "🔥",
          chapter: 3,
          chapterTitle: messages.tasks.chapter3,
        },
        {
          id: "achievement-recycling-hero",
          title: messages.tasks.achievementRecyclingHero,
          description: messages.tasks.achievementRecyclingHeroDesc,
          reward: 0,
          target: 500,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "points",
          icon: "♻️",
          chapter: 3,
          chapterTitle: messages.tasks.chapter3,
        },
        {
          id: "achievement-earth-guardian",
          title: messages.tasks.achievementEarthGuardian,
          description: messages.tasks.achievementEarthGuardianDesc,
          reward: 0,
          target: 1000,
          current: 0,
          completed: false,
          claimed: true,
          type: "achievement",
          category: "points",
          icon: "🌍",
          chapter: 3,
          chapterTitle: messages.tasks.chapter3,
        },
      ],
      unlocked: false,
      completed: false,
    },
  ];
}
