import { AchievementChapter } from "../types/tasks";

export const achievementChapters: AchievementChapter[] = [
  {
    id: 1,
    title: "Новичок",
    description: "Начните свой экологичный путь",
    icon: "🌱",
    requiredPoints: 0,
    achievements: [
      {
        id: "achievement-first-login",
        title: "Первый вход",
        description: "Войдите в приложение впервые",
        reward: 0,
        target: 1,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "visit",
        icon: "📱",
        chapter: 1,
        chapterTitle: "Новичок",
      },
      {
        id: "achievement-first-scan",
        title: "Первое сканирование",
        description: "Выполните первое сканирование отходов",
        reward: 0,
        target: 1,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "scan",
        icon: "📸",
        chapter: 1,
        chapterTitle: "Новичок",
      },
      {
        id: "achievement-first-eco-question",
        title: "Первый вопрос",
        description: "Задайте первый вопрос Эко-помощнику",
        reward: 0,
        target: 1,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "eco_assistant",
        icon: "🤖",
        chapter: 1,
        chapterTitle: "Новичок",
      },
      {
        id: "achievement-first-recycling-visit",
        title: "Первый маршрут",
        description: "Откройте карту переработки впервые",
        reward: 0,
        target: 1,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "map",
        icon: "🗺️",
        chapter: 1,
        chapterTitle: "Новичок",
      },
    ],
    unlocked: true,
    completed: false,
  },
  {
    id: 2,
    title: "Опытный",
    description: "Станьте активным эко-пользователем",
    icon: "🌿",
    requiredPoints: 250,
    achievements: [
      {
        id: "achievement-25-scans",
        title: "Мастер сканирования",
        description: "Выполните 25 сканирований отходов",
        reward: 0,
        target: 25,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "scan",
        icon: "📸",
        chapter: 2,
        chapterTitle: "Опытный",
      },
      {
        id: "achievement-20-questions",
        title: "Любознательный ум",
        description: "Задайте 20 вопросов Эко-помощнику",
        reward: 0,
        target: 20,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "eco_assistant",
        icon: "🤖",
        chapter: 2,
        chapterTitle: "Опытный",
      },
      {
        id: "achievement-7-day-streak",
        title: "Чемпион серии",
        description: "Поддерживайте серию 7 дней",
        reward: 0,
        target: 7,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "streak",
        icon: "🔥",
        chapter: 2,
        chapterTitle: "Опытный",
      },
      {
        id: "achievement-complete-weekly",
        title: "Покоритель недели",
        description: "Выполните все еженедельные задания",
        reward: 0,
        target: 3,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "recycling",
        icon: "⚔️",
        chapter: 2,
        chapterTitle: "Опытный",
      },
    ],
    unlocked: false,
    completed: false,
  },
  {
    id: 3,
    title: "Продвинутый",
    description: "Станьте мастером переработки",
    icon: "🌳",
    requiredPoints: 500,
    achievements: [
      {
        id: "achievement-75-scans",
        title: "Гуру сканирования",
        description: "Выполните 75 сканирований отходов",
        reward: 0,
        target: 75,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "scan",
        icon: "📸",
        chapter: 3,
        chapterTitle: "Продвинутый",
      },
      {
        id: "achievement-14-day-streak",
        title: "Двухнедельный чемпион",
        description: "Поддерживайте серию 14 дней",
        reward: 0,
        target: 14,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "streak",
        icon: "🔥",
        chapter: 3,
        chapterTitle: "Продвинутый",
      },
      {
        id: "achievement-recycling-hero",
        title: "Герой переработки",
        description: "Заработайте 500 Эко Поинтов",
        reward: 0,
        target: 500,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "points",
        icon: "♻️",
        chapter: 3,
        chapterTitle: "Продвинутый",
      },
      {
        id: "achievement-earth-guardian",
        title: "Хранитель Земли",
        description: "Заработайте 1000 Эко Поинтов",
        reward: 0,
        target: 1000,
        current: 0,
        completed: false,
        claimed: true,
        type: "achievement",
        category: "points",
        icon: "🌍",
        chapter: 3,
        chapterTitle: "Продвинутый",
      },
    ],
    unlocked: false,
    completed: false,
  },
];
