import React from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../contexts/AuthContext';
import { Language, useLanguage } from '../contexts/LanguageContext';
import { colors, radius, spacing } from '../theme';
import { ScreenContainer } from '../components/ScreenContainer';

export default function SettingsScreen() {
  const { user, signOut, removeAccount } = useAuth(); const { language, setAppLanguage, t } = useLanguage();
  const confirmSignOut = () => Alert.alert(t('settings.signOut'), t('settings.signOutConfirm'), [{ text: t('common.cancel'), style: 'cancel' }, { text: t('settings.signOut'), style: 'destructive', onPress: () => void signOut() }]);
  const confirmDelete = () => Alert.alert(t('settings.delete'), t('settings.deleteConfirm'), [{ text: t('common.cancel'), style: 'cancel' }, { text: t('settings.delete'), style: 'destructive', onPress: () => void removeAccount().catch(() => Alert.alert(t('common.error'), t('settings.deleteError'))) }]);
  const chooseLanguage = (next: Language) => { void setAppLanguage(next); };
  return <ScreenContainer><Text style={styles.title}>{t('settings.title')}</Text><Text style={styles.section}>{t('settings.general')}</Text><View style={styles.card}><Text style={styles.label}>{t('settings.language')}</Text><View style={styles.languages}><LanguageChoice label="Қазақша" selected={language === 'kk'} onPress={() => chooseLanguage('kk')} /><LanguageChoice label="Русский" selected={language === 'ru'} onPress={() => chooseLanguage('ru')} /></View></View><Text style={styles.section}>{t('settings.account')}</Text><View style={styles.card}><View style={styles.account}><View style={styles.avatar}><Text style={styles.avatarText}>{user?.full_name.slice(0, 1).toUpperCase()}</Text></View><View><Text style={styles.name}>{user?.full_name}</Text><Text style={styles.email}>{user?.email}</Text></View></View><Pressable style={styles.row} onPress={() => undefined}><Ionicons name="person-circle-outline" size={21} color={colors.primaryDark} /><Text style={styles.rowText}>{t('settings.accountInfo')}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable><Pressable style={styles.row} onPress={confirmSignOut}><Ionicons name="log-out-outline" size={21} color={colors.primaryDark} /><Text style={styles.rowText}>{t('settings.signOut')}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable><Pressable style={styles.row} onPress={confirmDelete}><Ionicons name="trash-outline" size={21} color="#B53C3C" /><View style={styles.deleteCopy}><Text style={styles.deleteText}>{t('settings.delete')}</Text><Text style={styles.deleteDescription}>{t('settings.deleteDescription')}</Text></View></Pressable></View></ScreenContainer>;
}
function LanguageChoice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.language, selected && styles.selected]}><Text style={[styles.languageText, selected && styles.selectedText]}>{label}</Text>{selected ? <Ionicons name="checkmark" size={16} color={colors.primaryDark} /> : null}</Pressable>; }
const styles = StyleSheet.create({ title: { color: colors.ink, fontSize: 30, fontWeight: '800', marginTop: spacing.sm }, section: { color: colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: 0.8, marginBottom: spacing.sm, marginTop: spacing.xl }, card: { backgroundColor: colors.card, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, padding: spacing.md }, label: { color: colors.ink, fontSize: 15, fontWeight: '700' }, languages: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md }, language: { alignItems: 'center', borderColor: colors.border, borderRadius: radius.sm, borderWidth: 1, flexDirection: 'row', gap: spacing.xs, paddingHorizontal: spacing.md, paddingVertical: 10 }, selected: { backgroundColor: colors.softGreen, borderColor: '#BFE7D1' }, languageText: { color: colors.muted, fontSize: 13, fontWeight: '700' }, selectedText: { color: colors.primaryDark }, account: { alignItems: 'center', flexDirection: 'row', paddingBottom: spacing.md }, avatar: { alignItems: 'center', backgroundColor: colors.softGreen, borderRadius: 18, height: 48, justifyContent: 'center', width: 48 }, avatarText: { color: colors.primaryDark, fontSize: 19, fontWeight: '800' }, name: { color: colors.ink, fontSize: 15, fontWeight: '800' }, email: { color: colors.muted, fontSize: 12, marginTop: 3 }, row: { alignItems: 'center', borderTopColor: colors.border, borderTopWidth: 1, flexDirection: 'row', paddingVertical: spacing.md }, rowText: { color: colors.ink, flex: 1, fontSize: 14, fontWeight: '700', marginLeft: spacing.md }, deleteCopy: { flex: 1, marginLeft: spacing.md }, deleteText: { color: '#B53C3C', fontSize: 14, fontWeight: '700' }, deleteDescription: { color: colors.muted, fontSize: 11, marginTop: 3 } });
