import React, { useState } from 'react';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '../contexts/AuthContext';
import { useLanguage } from '../contexts/LanguageContext';
import { colors, radius, spacing } from '../theme';
import { AuthStackParamList } from '../../App';

type Props = NativeStackScreenProps<AuthStackParamList, 'SignUp'>;
export default function SignUpScreen({ navigation }: Props) {
  const { signUpWithEmail, error, loading } = useAuth(); const { t } = useLanguage();
  const [name, setName] = useState(''); const [city, setCity] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [formError, setFormError] = useState('');
  const submit = async () => { setFormError(''); if (!name.trim() || !city.trim() || !email.trim() || !password || !confirm) return setFormError(t('auth.required')); if (!/^\S+@\S+\.\S+$/.test(email)) return setFormError(t('auth.invalidEmail')); if (password.length < 8) return setFormError(t('auth.passwordLength')); if (password !== confirm) return setFormError(t('auth.passwordMismatch')); try { await signUpWithEmail(name.trim(), email.trim(), password, city.trim()); } catch { /* Error is shown below. */ } };
  return <View style={styles.container}><Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>‹ {t('auth.signIn')}</Text></Pressable><Text style={styles.title}>{t('auth.signUp')}</Text><Text style={styles.subtitle}>QaitaJanaru</Text><TextInput placeholder={t('auth.name')} placeholderTextColor={colors.muted} style={styles.input} value={name} onChangeText={setName} /><TextInput placeholder={t('auth.city')} placeholderTextColor={colors.muted} style={styles.input} value={city} onChangeText={setCity} /><TextInput autoCapitalize="none" keyboardType="email-address" placeholder={t('auth.email')} placeholderTextColor={colors.muted} style={styles.input} value={email} onChangeText={setEmail} /><TextInput autoCapitalize="none" placeholder={t('auth.password')} placeholderTextColor={colors.muted} secureTextEntry style={styles.input} value={password} onChangeText={setPassword} /><TextInput autoCapitalize="none" placeholder={t('auth.confirmPassword')} placeholderTextColor={colors.muted} secureTextEntry style={styles.input} value={confirm} onChangeText={setConfirm} />{formError || error ? <Text style={styles.error}>{formError || t('auth.signUpError')}</Text> : null}<Pressable onPress={submit} disabled={loading} style={({ pressed }) => [styles.button, pressed && styles.pressed]}><Text style={styles.buttonText}>{loading ? t('common.loading') : t('auth.signUpAction')}</Text></Pressable><View style={styles.footer}><Text style={styles.footerText}>{t('auth.haveAccount')}</Text><Pressable onPress={() => navigation.goBack()}><Text style={styles.link}> {t('auth.signIn')}</Text></Pressable></View></View>;
}
const styles = StyleSheet.create({ container: { backgroundColor: colors.background, flex: 1, padding: spacing.xl, paddingTop: 60 }, back: { color: colors.primaryDark, fontSize: 14, fontWeight: '700' }, title: { color: colors.ink, fontSize: 30, fontWeight: '800', marginTop: spacing.xl }, subtitle: { color: colors.muted, fontSize: 14, marginTop: spacing.xs }, input: { backgroundColor: colors.card, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.ink, fontSize: 15, marginTop: spacing.md, padding: 15 }, error: { color: '#B53C3C', fontSize: 13, marginTop: spacing.sm }, button: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: radius.md, marginTop: spacing.lg, paddingVertical: 16 }, pressed: { opacity: 0.82 }, buttonText: { color: colors.card, fontSize: 16, fontWeight: '800' }, footer: { alignItems: 'center', flexDirection: 'row', justifyContent: 'center', marginTop: spacing.xl }, footerText: { color: colors.muted, fontSize: 13 }, link: { color: colors.primaryDark, fontSize: 13, fontWeight: '700' } });
