export const kk = {
  common: { loading: 'Жүктелуде...', cancel: 'Бас тарту', save: 'Сақтау', retry: 'Қайталау', error: 'Қате орын алды', notSet: 'Орнатылмаған', noActivity: 'Әзірге белсенділік жоқ' },
  nav: { home: 'Басты бет', scan: 'Сканерлеу', services: 'Қызметтер', profile: 'Профиль' },
  home: { welcome: 'Қайта қош келдіңіз', currentChallenge: 'Ағымдағы челлендж', viewAll: 'Барлығын көру', complete: 'орындалды', rewards: 'Сыйлықтар', seeAll: 'Барлығын көру', impact: 'Сіздің әсеріңіз', scan: 'Қалдықты сканерлеу', scanEyebrow: 'ӘСЕР ЕТІҢІЗ', scanText: 'Затты анықтап, дұрыс сұрыптаңыз.', current: 'Қазіргі челлендж', challengeScan: 'Осы аптада 5 затты сканерлеу', challengeBottles: '2 пластик бөтелкені қайта өңдеу', challengePoint: 'Сұрыптау нүктесіне бару' },
  rewards: { coffee: 'Эко кофе ваучері', transport: 'Қоғамдық көлік бонусы', bottle: 'Қайта пайдаланылатын бөтелке', bookstore: 'Кітап дүкеніне жеңілдік' },
  auth: { signIn: 'Кіру', signUp: 'Тіркелу', welcome: 'Қайта қош келдіңіз', email: 'Электрондық пошта', password: 'Құпиясөз', confirmPassword: 'Құпиясөзді растаңыз', name: 'Аты-жөні', city: 'Қала', signInAction: 'Кіру', signUpAction: 'Тіркелу', forgotPassword: 'Құпиясөзді ұмыттыңыз ба?', noAccount: 'Аккаунтыңыз жоқ па?', haveAccount: 'Аккаунтыңыз бар ма?', continueGoogle: 'Google арқылы жалғастыру', or: 'немесе', passwordMismatch: 'Құпиясөздер сәйкес келмейді', invalidEmail: 'Электрондық поштаны дұрыс енгізіңіз', required: 'Бұл жолды толтырыңыз', passwordLength: 'Құпиясөз кемінде 8 таңбадан тұруы керек', signInError: 'Кіру мүмкін болмады', signUpError: 'Тіркелу мүмкін болмады', googleError: 'Google арқылы кіру мүмкін болмады', forgotSoon: 'Құпиясөзді қалпына келтіру жақын арада қолжетімді болады' },
  services: { title: 'Қызметтер', subtitle: 'Ақылды қайта өңдеу үшін қажеттінің бәрі', map: 'Қайта өңдеу картасы', mapSub: 'Жақын нүктелер мен орталықтар', wasteGuide: 'Қалдықтар нұсқаулығы', wasteGuideSub: 'Сұрыптау және дайындау', challenges: 'Челлендждер', challengesSub: 'Белсенді және аяқталған мақсаттар', rankings: 'Рейтингтер', rankingsSub: 'Қауымдастық көшбасшылары', rewards: 'Сыйлықтар', rewardsSub: 'Eco Points жұмсаңыз', quiz: 'Eco Quiz', quizSub: 'Қысқа викториналар арқылы үйрену', hero: 'EcoHero картасы', heroSub: 'Сіздің цифрлық экопрофиліңіз', settings: 'Баптаулар', settingsSub: 'Қалаулар мен рұқсаттар' },
  profile: { title: 'Профиль', points: 'Eco Points', level: 'Эко деңгей', nextLevel: 'Келесі деңгейге прогресс', achievements: 'Жетістіктер', stats: 'Қайта өңдеу статистикасы', items: 'Қайта өңделген заттар', material: 'Қайта өңделген материал', co2: 'CO2 әсері', activity: 'Белсенділік', settings: 'Баптаулар', viewAchievements: 'Жетістіктерді көру', noAchievements: 'Әзірге жетістіктер жоқ', detailsNotSet: 'Жеке мәліметтер орнатылмаған' },
  settings: { title: 'Баптаулар', general: 'ЖАЛПЫ', language: 'Тіл', account: 'АККАУНТ', accountInfo: 'Аккаунт туралы', signOut: 'Шығу', signOutConfirm: 'Аккаунттан шығуды қалайсыз ба?', delete: 'Аккаунтты жою', deleteDescription: 'Аккаунт пен оған қатысты деректерді біржола жою', deleteConfirm: 'Бұл әрекет қайтымсыз. Аккаунтты және барлық деректерді жою керек пе?', deleteSuccess: 'Аккаунт жойылды', deleteError: 'Аккаунтты жою мүмкін болмады' },
  scan: { title: 'Қалдықты сканерлеу', subtitle: 'Затты суретке түсіріңіз, QaitaJanaru оны сұрыптауға көмектеседі.', ready: 'Сканерлеуге дайынсыз ба?', cameraNote: 'Камера арқылы анықтау қызметі кейін қосылады.', openCamera: 'Камераны ашу', cameraReady: 'Камера дайын', recent: 'Соңғы сканерлер', empty: 'Әзірге сканер жоқ' },
  achievements: { title: 'Жетістіктер', subtitle: 'Қайта өңдеу жолыңызды әр белеспен жалғастырыңыз.', current: 'ҚАЗІРГІ ЭКО ДЕҢГЕЙ', pointsToNext: 'келесі деңгейге ұпай', unlocked: 'ашылды', locked: 'Әлі ашылмаған', firstScan: 'Алғашқы скан', firstScanDescription: 'Алғашқы затыңызды анықтаңыз.', rookie: 'Қайта өңдеу бастаушысы', rookieDescription: '5 затты дұрыс қайта өңдеңіз.', tenItems: '10 зат қайта өңделді', tenItemsDescription: 'QaitaJanaru арқылы 10 затты қайта өңдеңіз.', weekly: 'Апталық серия', weeklyDescription: '7 түрлі күнде қайта өңдеңіз.', finisher: 'Челленджді аяқтаушы', finisherDescription: 'Алғашқы эко челленджді аяқтаңыз.', explorer: 'Эко зерттеуші', explorerDescription: 'Эко зерттеуші деңгейіне жетіңіз.', thousand: '1000 Eco Points', thousandDescription: '1000 Eco Points жинаңыз.' },
};
