export const ru = {
  common: { loading: 'Загрузка...', cancel: 'Отмена', save: 'Сохранить', retry: 'Повторить', error: 'Произошла ошибка', notSet: 'Не указано', noActivity: 'Активности пока нет' },
  nav: { home: 'Главная', scan: 'Сканировать', services: 'Сервисы', profile: 'Профиль' },
  home: { welcome: 'С возвращением', currentChallenge: 'Текущий челлендж', viewAll: 'Смотреть все', complete: 'выполнено', rewards: 'Награды', seeAll: 'Все награды', impact: 'Ваш вклад', scan: 'Сканировать отходы', scanEyebrow: 'ВНЕСИТЕ ВКЛАД', scanText: 'Определите предмет и отсортируйте его правильно.', current: 'Текущий челлендж', challengeScan: 'Сканировать 5 предметов на этой неделе', challengeBottles: 'Переработать 2 пластиковые бутылки', challengePoint: 'Посетить пункт сортировки' },
  rewards: { coffee: 'Ваучер на эко-кофе', transport: 'Бонус на общественный транспорт', bottle: 'Многоразовая бутылка', bookstore: 'Скидка в книжном магазине' },
  auth: { signIn: 'Войти', signUp: 'Регистрация', welcome: 'С возвращением', email: 'Электронная почта', password: 'Пароль', confirmPassword: 'Подтвердите пароль', name: 'Имя и фамилия', city: 'Город', signInAction: 'Войти', signUpAction: 'Создать аккаунт', forgotPassword: 'Забыли пароль?', noAccount: 'Нет аккаунта?', haveAccount: 'Уже есть аккаунт?', continueGoogle: 'Продолжить с Google', or: 'или', passwordMismatch: 'Пароли не совпадают', invalidEmail: 'Введите корректную почту', required: 'Заполните это поле', passwordLength: 'Пароль должен содержать не менее 8 символов', signInError: 'Не удалось войти', signUpError: 'Не удалось зарегистрироваться', googleError: 'Не удалось войти через Google', forgotSoon: 'Восстановление пароля скоро будет доступно' },
  services: { title: 'Сервисы', subtitle: 'Всё необходимое для разумной переработки', map: 'Карта переработки', mapSub: 'Ближайшие пункты и центры', wasteGuide: 'Гид по отходам', wasteGuideSub: 'Сортировка и подготовка', challenges: 'Челленджи', challengesSub: 'Активные и завершённые цели', rankings: 'Рейтинги', rankingsSub: 'Лидеры сообщества', rewards: 'Награды', rewardsSub: 'Тратьте Eco Points', quiz: 'Eco Quiz', quizSub: 'Учитесь через короткие викторины', hero: 'Карта EcoHero', heroSub: 'Ваш цифровой экопрофиль', settings: 'Настройки', settingsSub: 'Параметры и разрешения' },
  profile: { title: 'Профиль', points: 'Eco Points', level: 'Эко-уровень', nextLevel: 'Прогресс до следующего уровня', achievements: 'Достижения', stats: 'Статистика переработки', items: 'Переработано предметов', material: 'Переработано материала', co2: 'Воздействие CO2', activity: 'Активность', settings: 'Настройки', viewAchievements: 'Смотреть достижения', noAchievements: 'Достижений пока нет', detailsNotSet: 'Личные данные не указаны' },
  settings: { title: 'Настройки', general: 'ОБЩИЕ', language: 'Язык', account: 'АККАУНТ', accountInfo: 'Данные аккаунта', signOut: 'Выйти', signOutConfirm: 'Выйти из аккаунта?', delete: 'Удалить аккаунт', deleteDescription: 'Безвозвратно удалить аккаунт и связанные данные', deleteConfirm: 'Это действие нельзя отменить. Удалить аккаунт и все данные?', deleteSuccess: 'Аккаунт удалён', deleteError: 'Не удалось удалить аккаунт' },
  scan: { title: 'Сканировать отходы', subtitle: 'Сфотографируйте предмет, и QaitaJanaru поможет определить, как его сортировать.', ready: 'Готовы к сканированию?', cameraNote: 'Распознавание через камеру будет подключено позже.', openCamera: 'Открыть камеру', cameraReady: 'Камера готова', recent: 'Последние сканы', empty: 'Сканов пока нет' },
  achievements: { title: 'Достижения', subtitle: 'Продолжайте свой путь к более экологичным привычкам.', current: 'ТЕКУЩИЙ ЭКО-УРОВЕНЬ', pointsToNext: 'очков до следующего уровня', unlocked: 'открыто', locked: 'Ещё не открыто', firstScan: 'Первый скан', firstScanDescription: 'Определите свой первый предмет.', rookie: 'Новичок переработки', rookieDescription: 'Правильно переработайте 5 предметов.', tenItems: '10 предметов переработано', tenItemsDescription: 'Переработайте 10 предметов через QaitaJanaru.', weekly: 'Недельная серия', weeklyDescription: 'Перерабатывайте отходы в течение 7 разных дней.', finisher: 'Завершитель челленджа', finisherDescription: 'Завершите свой первый эко-челлендж.', explorer: 'Эко-исследователь', explorerDescription: 'Достигните уровня Эко-исследователь.', thousand: '1000 Eco Points', thousandDescription: 'Заработайте 1000 Eco Points.' },
};
