"""Initial migration

Revision ID: 7a28e72b3732
Revises: 
Create Date: 2026-07-27 22:14:38.481592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a28e72b3732'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_qr_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_qr_partners_id'), 'partner_qr_partners', ['id'], unique=False)
    op.create_index(op.f('ix_partner_qr_partners_name'), 'partner_qr_partners', ['name'], unique=True)
    op.create_table('partner_qr_rewards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('eco_points_required', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_qr_rewards_category_id'), 'partner_qr_rewards', ['category_id'], unique=False)
    op.create_index(op.f('ix_partner_qr_rewards_id'), 'partner_qr_rewards', ['id'], unique=False)
    op.create_table('recycling_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('waste_type', sa.String(), nullable=False),
    sa.Column('facility_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recycling_points_id'), 'recycling_points', ['id'], unique=False)
    op.create_index(op.f('ix_recycling_points_qr_identifier'), 'recycling_points', ['qr_identifier'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('eco_points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('level_progress_percent', sa.Integer(), nullable=True),
    sa.Column('total_experience', sa.Integer(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('total_scans', sa.Integer(), nullable=True),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.Date(), nullable=True),
    sa.Column('last_penalty_applied_date', sa.Date(), nullable=True),
    sa.Column('task_progress', sa.JSON(), nullable=True),
    sa.Column('claimed_rewards', sa.JSON(), nullable=True),
    sa.Column('completed_daily_tasks', sa.JSON(), nullable=True),
    sa.Column('completed_weekly_tasks', sa.JSON(), nullable=True),
    sa.Column('completed_achievement_chapters', sa.JSON(), nullable=True),
    sa.Column('last_daily_reset', sa.DateTime(), nullable=True),
    sa.Column('last_weekly_reset', sa.DateTime(), nullable=True),
    sa.Column('current_week_set', sa.String(), nullable=True),
    sa.Column('scans_used_today', sa.Integer(), nullable=True),
    sa.Column('assistant_messages_today', sa.Integer(), nullable=True),
    sa.Column('last_limit_reset_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('partner_qr_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('qr_scans', sa.Integer(), nullable=False),
    sa.Column('page_visits', sa.Integer(), nullable=False),
    sa.Column('route_requests', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_qr_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_qr_analytics_id'), 'partner_qr_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_partner_qr_analytics_partner_id'), 'partner_qr_analytics', ['partner_id'], unique=True)
    op.create_table('partner_qr_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('working_hours', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_qr_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_qr_branches_city'), 'partner_qr_branches', ['city'], unique=False)
    op.create_index(op.f('ix_partner_qr_branches_id'), 'partner_qr_branches', ['id'], unique=False)
    op.create_index(op.f('ix_partner_qr_branches_name'), 'partner_qr_branches', ['name'], unique=False)
    op.create_index(op.f('ix_partner_qr_branches_partner_id'), 'partner_qr_branches', ['partner_id'], unique=False)
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated', sa.Boolean(), nullable=False),
    sa.Column('request_ip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_codes_email'), 'password_reset_codes', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_codes_id'), 'password_reset_codes', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_codes_user_id'), 'password_reset_codes', ['user_id'], unique=False)
    op.create_table('qr_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recycling_point_id', sa.Integer(), nullable=False),
    sa.Column('qr_identifier', sa.String(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recycling_point_id'], ['recycling_points.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recycling_point_id', name='uq_user_point_qr_claim')
    )
    op.create_index(op.f('ix_qr_claims_id'), 'qr_claims', ['id'], unique=False)
    op.create_index(op.f('ix_qr_claims_recycling_point_id'), 'qr_claims', ['recycling_point_id'], unique=False)
    op.create_index(op.f('ix_qr_claims_user_id'), 'qr_claims', ['user_id'], unique=False)
    op.create_table('recycling_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recycling_point_id', sa.Integer(), nullable=False),
    sa.Column('plastic_bottles', sa.Integer(), nullable=False),
    sa.Column('glass', sa.Integer(), nullable=False),
    sa.Column('paper', sa.Integer(), nullable=False),
    sa.Column('metal_cans', sa.Integer(), nullable=False),
    sa.Column('batteries', sa.Integer(), nullable=False),
    sa.Column('electronics', sa.Integer(), nullable=False),
    sa.Column('cardboard', sa.Integer(), nullable=False),
    sa.Column('other_recyclable', sa.Integer(), nullable=False),
    sa.Column('total_points_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recycling_point_id'], ['recycling_points.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recycling_submissions_created_at'), 'recycling_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_recycling_submissions_id'), 'recycling_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_recycling_submissions_recycling_point_id'), 'recycling_submissions', ['recycling_point_id'], unique=False)
    op.create_index(op.f('ix_recycling_submissions_user_id'), 'recycling_submissions', ['user_id'], unique=False)
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('waste_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('eco_tip', sa.String(), nullable=False),
    sa.Column('recycling_advice', sa.String(), nullable=False),
    sa.Column('earned_points', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_history_id'), 'scan_history', ['id'], unique=False)
    op.create_table('partner_qr_branch_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['partner_qr_branches.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['partner_qr_rewards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'reward_id', name='uq_partner_qr_branch_reward')
    )
    op.create_index(op.f('ix_partner_qr_branch_rewards_branch_id'), 'partner_qr_branch_rewards', ['branch_id'], unique=False)
    op.create_index(op.f('ix_partner_qr_branch_rewards_id'), 'partner_qr_branch_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_partner_qr_branch_rewards_reward_id'), 'partner_qr_branch_rewards', ['reward_id'], unique=False)
    op.create_table('partner_qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_identifier', sa.String(), nullable=False),
    sa.Column('assigned_branch_id', sa.Integer(), nullable=True),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_branch_id'], ['partner_qr_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_qr_codes_assigned_branch_id'), 'partner_qr_codes', ['assigned_branch_id'], unique=True)
    op.create_index(op.f('ix_partner_qr_codes_id'), 'partner_qr_codes', ['id'], unique=False)
    op.create_index(op.f('ix_partner_qr_codes_qr_identifier'), 'partner_qr_codes', ['qr_identifier'], unique=True)
    op.create_table('partner_qr_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.String(), nullable=False),
    sa.Column('qr_code_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('eco_points_spent', sa.Integer(), nullable=False),
    sa.Column('eco_points_balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['partner_qr_branches.id'], ),
    sa.ForeignKeyConstraint(['qr_code_id'], ['partner_qr_codes.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['partner_qr_rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_qr_exchanges_branch_id'), 'partner_qr_exchanges', ['branch_id'], unique=False)
    op.create_index(op.f('ix_partner_qr_exchanges_id'), 'partner_qr_exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_partner_qr_exchanges_qr_code_id'), 'partner_qr_exchanges', ['qr_code_id'], unique=False)
    op.create_index(op.f('ix_partner_qr_exchanges_reward_id'), 'partner_qr_exchanges', ['reward_id'], unique=False)
    op.create_index(op.f('ix_partner_qr_exchanges_user_id'), 'partner_qr_exchanges', ['user_id'], unique=False)
    op.create_table('partner_qr_receipts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('reward_title', sa.String(), nullable=False),
    sa.Column('eco_points_spent', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['partner_qr_exchanges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_qr_receipts_exchange_id'), 'partner_qr_receipts', ['exchange_id'], unique=True)
    op.create_index(op.f('ix_partner_qr_receipts_id'), 'partner_qr_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_partner_qr_receipts_user_id'), 'partner_qr_receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_qr_receipts_user_id'), table_name='partner_qr_receipts')
    op.drop_index(op.f('ix_partner_qr_receipts_id'), table_name='partner_qr_receipts')
    op.drop_index(op.f('ix_partner_qr_receipts_exchange_id'), table_name='partner_qr_receipts')
    op.drop_table('partner_qr_receipts')
    op.drop_index(op.f('ix_partner_qr_exchanges_user_id'), table_name='partner_qr_exchanges')
    op.drop_index(op.f('ix_partner_qr_exchanges_reward_id'), table_name='partner_qr_exchanges')
    op.drop_index(op.f('ix_partner_qr_exchanges_qr_code_id'), table_name='partner_qr_exchanges')
    op.drop_index(op.f('ix_partner_qr_exchanges_id'), table_name='partner_qr_exchanges')
    op.drop_index(op.f('ix_partner_qr_exchanges_branch_id'), table_name='partner_qr_exchanges')
    op.drop_table('partner_qr_exchanges')
    op.drop_index(op.f('ix_partner_qr_codes_qr_identifier'), table_name='partner_qr_codes')
    op.drop_index(op.f('ix_partner_qr_codes_id'), table_name='partner_qr_codes')
    op.drop_index(op.f('ix_partner_qr_codes_assigned_branch_id'), table_name='partner_qr_codes')
    op.drop_table('partner_qr_codes')
    op.drop_index(op.f('ix_partner_qr_branch_rewards_reward_id'), table_name='partner_qr_branch_rewards')
    op.drop_index(op.f('ix_partner_qr_branch_rewards_id'), table_name='partner_qr_branch_rewards')
    op.drop_index(op.f('ix_partner_qr_branch_rewards_branch_id'), table_name='partner_qr_branch_rewards')
    op.drop_table('partner_qr_branch_rewards')
    op.drop_index(op.f('ix_scan_history_id'), table_name='scan_history')
    op.drop_table('scan_history')
    op.drop_index(op.f('ix_recycling_submissions_user_id'), table_name='recycling_submissions')
    op.drop_index(op.f('ix_recycling_submissions_recycling_point_id'), table_name='recycling_submissions')
    op.drop_index(op.f('ix_recycling_submissions_id'), table_name='recycling_submissions')
    op.drop_index(op.f('ix_recycling_submissions_created_at'), table_name='recycling_submissions')
    op.drop_table('recycling_submissions')
    op.drop_index(op.f('ix_qr_claims_user_id'), table_name='qr_claims')
    op.drop_index(op.f('ix_qr_claims_recycling_point_id'), table_name='qr_claims')
    op.drop_index(op.f('ix_qr_claims_id'), table_name='qr_claims')
    op.drop_table('qr_claims')
    op.drop_index(op.f('ix_password_reset_codes_user_id'), table_name='password_reset_codes')
    op.drop_index(op.f('ix_password_reset_codes_id'), table_name='password_reset_codes')
    op.drop_index(op.f('ix_password_reset_codes_email'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.drop_index(op.f('ix_partner_qr_branches_partner_id'), table_name='partner_qr_branches')
    op.drop_index(op.f('ix_partner_qr_branches_name'), table_name='partner_qr_branches')
    op.drop_index(op.f('ix_partner_qr_branches_id'), table_name='partner_qr_branches')
    op.drop_index(op.f('ix_partner_qr_branches_city'), table_name='partner_qr_branches')
    op.drop_table('partner_qr_branches')
    op.drop_index(op.f('ix_partner_qr_analytics_partner_id'), table_name='partner_qr_analytics')
    op.drop_index(op.f('ix_partner_qr_analytics_id'), table_name='partner_qr_analytics')
    op.drop_table('partner_qr_analytics')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recycling_points_qr_identifier'), table_name='recycling_points')
    op.drop_index(op.f('ix_recycling_points_id'), table_name='recycling_points')
    op.drop_table('recycling_points')
    op.drop_index(op.f('ix_partner_qr_rewards_id'), table_name='partner_qr_rewards')
    op.drop_index(op.f('ix_partner_qr_rewards_category_id'), table_name='partner_qr_rewards')
    op.drop_table('partner_qr_rewards')
    op.drop_index(op.f('ix_partner_qr_partners_name'), table_name='partner_qr_partners')
    op.drop_index(op.f('ix_partner_qr_partners_id'), table_name='partner_qr_partners')
    op.drop_table('partner_qr_partners')
    # ### end Alembic commands ###
